- name: test win_chocolatey installs
  hosts: win2016
  vars:
  tasks:
  - name: install Chocolatey 0.10.15 - version with bug fix
    win_chocolatey:
      name: chocolatey
      state: latest

  - name: install jre8
    win_chocolatey:
      name: jre8
      version: '8.0.211'
      state: present
      
  - name: install UrlRewrite for IIS
    win_chocolatey:
      name: urlrewrite
      state: latest

  - name: install powershell core
    win_chocolatey:
      name: powershell-core
      state: latest
      
  - name: configure tomcat
    win_chocolatey:
      name: tomcat
      version: 9.0.20
      state: present

