- name: example play to run on a Windows server
  hosts: win2016
  tasks:
  - name: Copy bin folder
    win_copy:
      src: ../server/mrpweb/bin/
      dest: D:\IIS\Api\Api.MrpWeb\bin
      
  - name: Copy web config file
    win_copy:
      src: ../server/mrpweb/Web.config
      dest: D:\IIS\Api\Api.MrpWeb\Web.config

 # - name: Copy client side
 #   win_copy:
 #     src: ../server/mrpweb/client/
 #     dest: D:\IIS\Client\Client.MrpWeb

